### ISSUE TITLE
New Deploy Checklist July 2024

### ISSUE THREAD

**Issue by Janell-Huyck** [uclibs/treatment_database#522]
### Pre-Deploy steps
My change request:
https://ituc.service-now.com/nav_to.do?uri=%2Fchange_request.do%3Fsys_id%3D9a20601193d74a50b23cbf0e1dba10a5%26sysparm_view%3D%26sysparm_domain%3Dnull%26sysparm_domain_scope%3Dnull
## Pre-Deploy steps
- [x] Prepare the QA environment
  * drop QA database
  * run QA migrations
  * run QA seeds (includes creating the needed accounts)
- [ ] Merge "qa" into "main"
  * `git fetch origin`
  * `git checkout main`
  * `git pull origin main`
  * `git merge qa`
  * resolve any conflicts
  * `git push origin main`
- [x] [Create a "Release" on Github](https://github.com/uclibs/treatment_database/releases).  When this is published and not just a draft, it will create a "tag" with the version number you used in the release, removing the need to manually push a tag number.  Set this as a pre-release.
- [x] [Submit security scan](https://ituc.service-now.com/sp?id=sc_cat_item&sys_id=7837d01c1bdb641047c6a6c6bc4bcbfb) - requested date back is at least one week before you intend to present to change management.
- [ ] [Submit accessibility scan if needed](https://ituc.service-now.com/sp?id=sc_cat_item&sys_id=9d5a31951b798810e30db992cc4bcb08)
- [ ] [Submit Change Request](https://ituc.service-now.com/nav_to.do), setting the deployment date at least one week after presenting to change management.
- [ ] Notify the TD team (Holly Prochaska) of incoming changes and the expected deployment date
- [ ] Make sure NVM is installed on libapps
- [ ] Make sure Ruby 3.3.3 is installed on libapps

### Deploy Steps
- [ ] Run `cap main deploy`
- [ ] Verify app is running correctly:
  - App can be accessed at [the production website](https://libapps.libraries.uc.edu/treatment_database).
  - CSS is present - grey banner on logging in, red trash can icons on the records index page.
  - Admin can log in.
  - Admin can access appropriate menus.
  - A report can be generated and viewed.
  - A record can be viewed.
  - Admin can log out.

### Troubleshooting:

- Check that migrations were run if needed (None expected this time.)
- Look at file structure in libapps and see if public files were correctly generated.

### Reverting Changes
If deploy is unsuccessful, revert to latest tagged version (1.0.2) as follows:

#### On local terminal:
1. download most recent tags with `git fetch --tags`
2. checkout the correct tag with `git checkout 1.0.2`
3. change **config/deploy/main** :branch from `main` to `1.0.2`
4. deploy with `cap main deploy`
5. change the cap lock in **config/deploy.rb** if required by prompt in the terminal (likely to 3.18.1) and re-deploy
6. verify successful re-deployment

### Post-Deployment Steps:

- [ ]  [Close the milestone if not already done](https://github.com/uclibs/treatment_database/milestones)
- [ ]  Close the Github deployment issue
- [ ]  Mark the change request as completed
- [ ] Set the Github release as the most recent version
- [ ] Update the App Portfolio

**Comment by Janell-Huyck** [comment]
Moved to Jira
